### ISSUE TITLE
Panda Syntax

### ISSUE THREAD

**Issue by siamak** [DHedgecock/vscode-panda-extended#2]
Hello @DHedgecock. I'm Siamak Mokhtari, Creator of Panda Theme. Today installed your theme on VSCode. That's great and I love it. I want to merge this repo with [Panda Snytax](https://marketplace.visualstudio.com/items?itemName=tinkertrain.theme-panda). Please send an Invitation on Visualstudio marketplace

**Comment by rafa-acioly** [comment]
How can i install this extension?

**Comment by DHedgecock** [comment]
Hello Siamak,
I'm glad you like the theme. How do you want to merge with the other VSCode Panda? The setup of this repo is a bit different than the tmTheme in the other repo:
1. The styles and colors are kept in yaml files in the [/themes] (https://github.com/DHedgecock/vscode-panda-extended/tree/master/themes) dir.
2. The [build.js](https://github.com/DHedgecock/vscode-panda-extended/blob/master/build.js) file pulls in all the colors/themes to build out a JSON file in /dist
3. The base tokens in [panda-base.yaml](https://github.com/DHedgecock/vscode-panda-extended/blob/master/themes/panda-base.yaml) are different than the base tokens from the other VSCode Panda.

Are you wanting to pull this repo in to the other extension and replace it?

**Comment by siamak** [comment]
I want to merge two repos and maintained a package. What's your Idea?

**Comment by DHedgecock** [comment]
As they are now, this repo would need to override the other repo.

Hello @tinkertrain, would you be interested in this?

**Comment by siamak** [comment]
Now I opened your theme on my VSCode. That's great. Thanks ;)

**Comment by siamak** [comment]
If you can in new version please add contrast to `workbench` like, http://panda.siamak.work/screenshots/html.jpg

**Comment by DHedgecock** [comment]
You mean contrast between the sidebar and the code text?

**Comment by siamak** [comment]
Yeess.

**Comment by siamak** [comment]
Do you have telegram (telegram.org) or Skype account? I want to chat with you :)
@DHedgecock

**Comment by tinkertrain** [comment]
Hi @DHedgecock sorry for the late response, yes I think we should merge them, let me know how to go about it.

**Comment by siamak** [comment]
@DHedgecock @tinkertrain Hey guys! Are you ready to merge repos to one?

**Comment by tinkertrain** [comment]
Yep, let me know what I need to do

**Comment by siamak** [comment]
@tinkertrain Do you have account on telegram or skype?

**Comment by DHedgecock** [comment]
Ok, I published the updates to Panda Extended. I'm going to make a PR now on @tinkertrain original repo. After that version is updated I will add a [DEPRECATED] to this extension's name and update the README pointing to the other package. After that I'll unpublish this extension 👍

**Comment by siamak** [comment]
@DHedgecock Thanks. I have permission to publish new version on [Panda VSCode](https://marketplace.visualstudio.com/items?itemName=tinkertrain.theme-panda) How can I publish it? do you have document?

**Comment by siamak** [comment]
@DHedgecock @tinkertrain Thanks Guys. I had published to [Panda VSCode](https://marketplace.visualstudio.com/items?itemName=tinkertrain.theme-panda) Well done ;) Happy Hacking!

**Comment by tinkertrain** [comment]
@siamak Awesome! By the way maybe we should move the repo to the Panda org?

**Comment by siamak** [comment]
@tinkertrain Yes If we can do that, that's awesome. Do you can search about migratation from a repo to another repo in `vsce`?

**Comment by siamak** [comment]
@DHedgecock hi. Please send your email account in visual studio code extension `vsce` for invited you as contributor in Panda project.

**Comment by siamak** [comment]
Hey guys. Panda🐼 theme is one of the best vscode themes: https://scotch.io/bar-talk/best-vs-code-themes-of-2017
Congratulation 😍👍🏻🎁
